"use strict";
exports.HEROES = [
    { id: 1009610, name: 'Peter Parker', alias: 'Spider Man', story: 'Bitten by a radioactive spider, high school student Peter Parker gained the speed, strength and powers of a spider. Adopting the name Spider-Man, Peter hoped to start a career using his new abilities. Taught that with great power comes great responsibility, Spidey has vowed to use his powers to help people.' },
    { id: 1009262, name: 'Matt Murdock', alias: 'Daredevil', story: 'Abandoned by his mother, Matt Murdock was raised by his father, boxer "Battling Jack" Murdock, in Hell\'\s Kitchen. Realizing that rules were needed to prevent people from behaving badly, young Matt decided to study law; however, when he saved a man from an oncoming truck, it spilled a radioactive cargo that rendered Matt blind while enhancing his remaining senses. Under the harsh tutelage of blind martial arts master Stick, Matt mastered his heightened senses and became a formidable fighter.' },
    { id: 1009367, name: 'Danny Rand', alias: 'The Iron Fist', story: 'When Danny Rand was 10-years old, he survived a mysterious plane crash that claimed the lives of his extremely wealthy parents. Rescued by warrior monks, Danny grew up in the of city of K\'un-Lun, where he endured harsh conditions, but also trained to be a fierce warrior.' },
    { id: 4, name: 'Oliver Queen', alias: 'Green Arrow', story: 'Spoiled billionaire Oliver Queen came home with an entirely different personality—and a newfound purpose in life. Completely self-absorbed and never caring about anything but himself, Queen was on a leisurely sailing trip when his assistant betrayed him, leaving him for dead on a desolate remote island.' },
    { id: 5, name: 'Barry Allen', alias: 'Flash', story: 'Young Barry Allen’s life stopped the minute his mother was murdered. The true killer never found, its mystery obsessed Barry, driving him to become a forensic scientist. Consumed by his work, he spent his life chained to his desk, solving every case that flew across it. But when a freak lightning bolt hits a nearby shelf in his lab, Barry receives super-speed, becoming the Flash.' },
    { id: 1009268, name: 'Wade Wilson', alias: 'Deadpool', story: 'Wade Wilson\'\s early life is mostly unknown. Learning that he had contracted cancer, Wilson broke up with Vanessa rather than force her to remain with a terminally ill man. In Canada, he was offered hope in the form of Department K, a special weapons development branch of the Canadian government. Wilson became a test subject in Department K\'\s branch of the joint U.S./Canadian superhuman enhancement project, the Weapon X Program' },
    { id: 1009257, name: 'Scott Summers', alias: 'Cyclops', story: 'Scott Summers was the first of two sons born to Major Christopher Summers, a test pilot for the U.S. Air Force, and his wife Katherine. Christopher was flying his family home from vacation when their plane was attacked by a spacecraft from the interstellar Shi\'\ar Empire. To save their lives, Katherine pushed Scott and his brother Alex out of the plane with the only available parachute. Scott suffered a head injury upon landing, thus forever preventing him from controlling his mutant power by himself.' },
    { id: 1009356, name: 'Johnny Storm', alias: 'Human Torch', story: 'Following his sister, Sue, Johnny joined Reed Richards\'\ crew in a space flight. Riddled with cosmic radiation, Johnny transformed into a flaming monster when the flight crashed back to earth. Calling himself Human Torch in tribute to the World War II era hero of the same name' },
    { id: 1009282, name: 'Dr. Stephen Vincent Strange', alias: 'Dr. Strange', story: 'Circa 1963, Strange was in a car accident that severely damaged the nerves in his hands, ending his surgical career. Too vain to accept positions as a consultant or assistant, Strange sought a cure and pursued every available treatment, legitimate or not, soon depleting his fortune; After hearing rumors of the mystical Ancient One, a desperate Strange pawned his last possessions for a ticket to the East and found the Ancient One\'\s Tibetan palace.' },
    { id: 1009368, name: 'Tony Stark', alias: 'Iron Man', story: 'Wounded, captured and forced to build a weapon by his enemies, billionaire industrialist Tony Stark instead created an advanced suit of armor to save his life and escape captivity. Now with a new outlook on life, Tony uses his money and intelligence to make the world a safer, better place as Iron Man.' },
];
//# sourceMappingURL=mock-heroes.js.map